TraceboxCollector/config/routes.rb
Rails.application.routes.draw do
  post "/curl" => "pcap_uploads#curl"
  get '*path' => redirect('/')

end

TraceboxCollector/app/models/pcap_upload.rb
require 'carrierwave/orm/activerecord'

class PcapUpload < ActiveRecord::Base
	mount_uploader :uploader, PcapUploader
	
end

TraceboxCollector/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TraceboxCollector/app/controllers/pcap_uploads_controller.rb
class PcapUploadsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_pcap_upload, only: [:show, :edit, :update, :destroy]

  # GET /pcap_uploads
  # GET /pcap_uploads.json
  def index
    @pcap_uploads = PcapUpload.all
  end

  # GET /pcap_uploads/1
  # GET /pcap_uploads/1.json
  def show
  end

  # GET /pcap_uploads/new
  def new
    @pcap_upload = PcapUpload.new
  end

  # GET /pcap_uploads/1/edit
  def edit
  end

  #POST /pcap_uploads/curl
  def curl
    filename||= "#{SecureRandom.urlsafe_base64}.pcap"
    #Rails.logger.debug params.inspect
    #puts params[:file].inspect
    data = params[:file]
    t=  data.tempfile
    File.open(File.join(Rails.root, "/public/uploads/" << filename), 'w+b') { |f| 
        t.rewind
        while  !t.eof?
          f.write(t.read)
        end
    }


    respond_to do |format|
        format.json { head :ok }
    end
  end



  # POST /pcap_uploadsx
  # POST /pcap_uploads.json
  def create
    @pcap_upload = PcapUpload.new(pcap_upload_params)

    @pcap_upload.uploader.store!(File.open(@pcap_upload.uploader.current_path))
    respond_to do |format|
      if @pcap_upload.save!
        format.html { redirect_to @pcap_upload, notice: 'Pcap upload was successfully created.' }
        format.json { render :show, status: :created, location: @pcap_upload }
      else
        format.html { render :new }
        format.json { render json: @pcap_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pcap_uploads/1
  # PATCH/PUT /pcap_uploads/1.json
  def update
    respond_to do |format|
      if @pcap_upload.update(pcap_upload_params)
        format.html { redirect_to @pcap_upload, notice: 'Pcap upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @pcap_upload }
      else
        format.html { render :edit }
        format.json { render json: @pcap_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pcap_uploads/1
  # DELETE /pcap_uploads/1.json
  def destroy
    @pcap_upload.destroy
    respond_to do |format|
      format.html { redirect_to pcap_uploads_url, notice: 'Pcap upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pcap_upload
      @pcap_upload = PcapUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pcap_upload_params
      params.require(:pcap_upload).permit(:script, :source, :uploader)
    end
end

TraceboxCollector/app/helpers/application_helper.rb
module ApplicationHelper
end

TraceboxCollector/app/helpers/pcap_uploads_helper.rb
module PcapUploadsHelper
end

TraceboxCollector/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TraceboxCollector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

TraceboxCollector/app/views/pcap_uploads/_form.html.erb
<%= form_for @pcap_upload, :html => {:multipart => true} do |f| %>
  <% if @pcap_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pcap_upload.errors.count, "error") %> prohibited this pcap_upload from being saved:</h2>

      <ul>
      <% @pcap_upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :script %><br>
    <%= f.number_field :script %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div>
    <label>Pcap</label>
    <%= f.file_field :uploader%>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TraceboxCollector/app/views/pcap_uploads/edit.html.erb
<h1>Editing Pcap Upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @pcap_upload %> |
<%= link_to 'Back', pcap_uploads_path %>

TraceboxCollector/app/views/pcap_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pcap Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Script</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    
    <% @pcap_uploads.each do |pcap_upload| %>
      <tr>
        <td><%= pcap_upload.script %></td>
        <td><%= pcap_upload.source %></td>
        <td><%= link_to 'Show', pcap_upload %></td>
        <td><%= link_to 'Edit', edit_pcap_upload_path(pcap_upload) %></td>
        <td><%= link_to 'Destroy', pcap_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pcap upload', new_pcap_upload_path %>

TraceboxCollector/app/views/pcap_uploads/new.html.erb
<h1>New Pcap Upload</h1>

<%= render 'form' %>

<%= link_to 'Back', pcap_uploads_path %>

TraceboxCollector/app/views/pcap_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Script:</strong>
  <%= @pcap_upload.script %>
</p>

<p>
  <strong>Source:</strong>
  <%= @pcap_upload.source %>
</p>

<%= link_to 'Edit', edit_pcap_upload_path(@pcap_upload) %> |
<%= link_to 'Back', pcap_uploads_path %>